### ISSUE TITLE
registration crashes when given a name of exactly 15 characters in length

### ISSUE THREAD

**Issue by TwilightFlower** [exalpha-dev/exalpha-dev.github.io#1]

**Comment by suspecting** [comment]
I think this was the standard, even during release versions.

**Comment by debil03311** [comment]
Yeah, that happens because of this part:
```javascript
var bytes = ''
  , counter = 0;

for (var i = 0; i < username.length; i++) {
  numberString0 += (70 - (26 - (name.charCodeAt(i) - 'A'.charCodeAt(0)))).toString();
  counter++; // 15
}

bytes = EndBytes[Math.floor(Math.random() * EndBytes.length)].toString();
counter++; // 16
var numberString1 = numberString0;

while (counter != 15) {
  numberString1 += (10 + Math.floor(Math.random() * 89)).toString();
  counter++;
}
```
As you can see, if your username is 15 characters long that `counter` variable ends up having a value of `16`, and so it gets incremented infinitely in a pointless effort of trying to become 15 again. You can easily fix it by removing the second `counter++` since the function has a guard clause for usernames longer than 15 characters.

**Comment by exalpha-dev** [comment]
Fixed with https://github.com/exalpha-dev/exalpha-dev.github.io/commit/f304a93485874bd3c6a65ab94a59fe78bb4d8aa2
